### ISSUE TITLE
Usability and license

### ISSUE THREAD

**Issue by Johni0702** [sile/rtp#1]
This seems to be the most complete, pure-rust implementation of RTP I could find (and the only one supporting SRTP). How usable is it? Has it ever been tested against implementations in other languages?

Also, there seems to be no mention of any license anywhere. Would you mind publishing it under some permissive license, e.g. the MIT license which you seem to be using with lots of your other projects?

**Comment by sile** [comment]
`rtp` crate was used for developing a hobby WebRTC server last year (it is a private repository).
The server worked somehow but `rtp` includes a lot of ad-hoc  codes and seems to be incompleted.
So I think the quality of this crate is not production ready.

P.S. I added the MIT-LICENSE file to the master branch

**Comment by Johni0702** [comment]
Thanks for the quick answer, adding the license and this lib in general.

My goal is to bridge a 3rd-party voice protocol to webrtc and this lib will probably be a good starting point to build on. Originally I was trying to use gstreamer's webrtcbin but it doesn't even support reconfiguration after the initial handshake, so I figured I might as well go all in and see if I can do it in mostly pure rust (+ openssl).

Depending on how far I actually pull this through, I'll probably shoot you a few PRs if you don't mind:
- sending of SRTP, i.e. encryption + hmac (only receiving direction is currently implemented)
- DTLS-SRTP ([rfc5764](https://tools.ietf.org/html/rfc5764))
- some smaller things here and there in the existing code
- probably more as I learn about it

**Comment by sile** [comment]
>  I'll probably shoot you a few PRs if you don't mind:

Your contribution is very welcome!
