### ISSUE TITLE
rtp compilation error since rustc 1.49.0 (possible earlier)

### ISSUE THREAD

**Issue by HenkKalkwater** [sile/rtp#2]
I'm using this library indirectly via another project and it seems that since at least since "rustc 1.49.0", possible earlier, 
this library does not compile any more. I myself have not used Rust that much, so I don't know the exact cause. If I have the time I'll look into it later and make a pull request if I'm able to fix it, but in the meanwhile I wanted to notify you.

When building, I get the following error.
```
error[E0282]: type annotations needed
   --> /build/mumblewebproxy-vendor.tar.gz/rtp/src/rfc3711.rs:476:19
    |
475 |         let iv = iv ^ (BigUint::from(1_u8) << (context.session_encr_key.len() * 8));
    |             -- consider giving `iv` a type
476 |         let iv = &iv.to_bytes_be()[1..context.session_encr_key.len() + 1];
    |                   ^^ cannot infer type
    |
    = note: type must be known at this point

error[E0282]: type annotations needed
   --> /build/mumblewebproxy-vendor.tar.gz/rtp/src/rfc3711.rs:512:19
    |
511 |         let iv = iv ^ (BigUint::from(1_u8) << (context.session_encr_key.len() * 8));
    |             -- consider giving `iv` a type
512 |         let iv = &iv.to_bytes_be()[1..context.session_encr_key.len() + 1];
    |                   ^^ cannot infer type
    |
    = note: type must be known at this point

error: aborting due to 2 previous errors
```

**Comment by sile** [comment]
Thank you for reporting this issue.

However, I cannot reproduce that in my environment (with rustc-v1.50.0).
The commends I executed were as follows:
```console
$ uname -a
Linux LAPTOP-PP3DNNQN 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 GNU/Linux

$ rustc --version
rustc 1.50.0 (cb75ad5db 2021-02-10)

$ git clone git://github.com/sile/rtp
$ cd rtp/

$ cargo test
...
running 3 tests
test tests::it_works ... ok
test rfc3711::test::rtp_decryption_works ... ok
test rfc3711::test::rtcp_decryption_works ... ok

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests rtp

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

Could you give me more information to reproduce the issue?

**Comment by sile** [comment]
FYI: I re-executed the above commands with rustc-v1.49.0, but there were still no errors:
```console
$ rustup default 1.49.0
$ rustc --version
rustc 1.49.0 (e1884a8e3 2020-12-29)

$ cargo test
...
running 3 tests
test tests::it_works ... ok
test rfc3711::test::rtp_decryption_works ... ok
test rfc3711::test::rtcp_decryption_works ... ok

test result: ok. 3 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by sile** [comment]
I found that the error messages you wrote refer to the line `rfc3711.rs:476` and `rfc3711.rs:512` despite that the `rfc3711.rs` file on the master branch of this repo has only 387 lines. So, I guess, the "another project" uses a forked version of `rtp` and this problem is specific on the variant.

**Comment by HenkKalkwater** [comment]
You're completely right, I made a mistake here, because it's actually one of the forks of this package, to be exactly [the dtls-srtp branch of Johni0702's fork](https://github.com/Johni0702/rtp/tree/dtls-srtp). I'll take this issue over there.

The environment I was building on is [this revision of nixos-unstable](https://releases.nixos.org/nixos/unstable/nixos-21.05pre271938.c7d0dbe094c) by the way.

Sorry for the inconvenience.

**Comment by sile** [comment]
No problem :)
Thank you for sharing the detail.
